from __future__ import annotations

import os
import sqlite3
from contextlib import closing
from datetime import date, datetime, timedelta
from io import BytesIO
from pathlib import Path

from flask import Flask, redirect, render_template, request, send_file, url_for
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def create_app(test_config: dict | None = None) -> Flask:
    app = Flask(__name__)

    app.config.from_mapping(
        DATABASE=os.environ.get("REVENUE_DB", str(Path(app.instance_path) / "revenue.db")),
        SECRET_KEY="dev",
    )

    if test_config:
        app.config.update(test_config)

    Path(app.instance_path).mkdir(parents=True, exist_ok=True)
    init_db(app)

    @app.get("/")
    def index():
        sales = get_recent_sales(app)
        summary = get_summary_metrics(app)
        weekly_breakdown = get_weekly_breakdown(app)
        monthly_breakdown = get_monthly_breakdown(app)
        return render_template(
            "index.html",
            sales=sales,
            summary=summary,
            weekly_breakdown=weekly_breakdown,
            monthly_breakdown=monthly_breakdown,
            today=date.today().isoformat(),
        )

    @app.post("/sales")
    def add_sale():
        sale_date = request.form.get("sale_date", "").strip()
        customer_name = request.form.get("customer_name", "Walk-in").strip() or "Walk-in"
        item_description = request.form.get("item_description", "General sale").strip() or "General sale"
        payment_method = request.form.get("payment_method", "Cash").strip() or "Cash"
        amount_raw = request.form.get("amount", "0").strip()

        try:
            parsed_date = datetime.strptime(sale_date, "%Y-%m-%d").date()
            amount = float(amount_raw)
            if amount <= 0:
                raise ValueError("Amount must be positive")
        except ValueError:
            return redirect(url_for("index"))

        with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
            conn.execute(
                """
                INSERT INTO sales (sale_date, customer_name, item_description, amount, payment_method)
                VALUES (?, ?, ?, ?, ?)
                """,
                (parsed_date.isoformat(), customer_name, item_description, amount, payment_method),
            )
            conn.commit()

        return redirect(url_for("index"))

    @app.get("/receipt/<int:sale_id>.pdf")
    def sale_receipt_pdf(sale_id: int):
        sale = get_sale_by_id(app, sale_id)
        if sale is None:
            return "Receipt not found", 404

        pdf_buffer = BytesIO()
        receipt = canvas.Canvas(pdf_buffer, pagesize=A4)
        width, height = A4

        receipt.setFont("Helvetica-Bold", 16)
        receipt.drawString(50, height - 60, "Sales Receipt")

        receipt.setFont("Helvetica", 11)
        fields = [
            ("Receipt #", str(sale["id"])),
            ("Date", sale["sale_date"]),
            ("Customer", sale["customer_name"]),
            ("Description", sale["item_description"]),
            ("Payment", sale["payment_method"]),
            ("Amount", f"${sale['amount']:.2f}"),
        ]

        y_pos = height - 110
        for key, value in fields:
            receipt.drawString(50, y_pos, f"{key}: {value}")
            y_pos -= 24

        receipt.setFont("Helvetica-Oblique", 10)
        receipt.drawString(50, y_pos - 12, "Generated by Revenue Tracker")

        receipt.showPage()
        receipt.save()

        pdf_buffer.seek(0)
        return send_file(
            pdf_buffer,
            mimetype="application/pdf",
            as_attachment=True,
            download_name=f"receipt-{sale_id}.pdf",
        )

    return app


def init_db(app: Flask) -> None:
    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sales (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sale_date TEXT NOT NULL,
                customer_name TEXT NOT NULL,
                item_description TEXT NOT NULL,
                amount REAL NOT NULL,
                payment_method TEXT NOT NULL
            )
            """
        )
        conn.commit()


def get_recent_sales(app: Flask, limit: int = 12) -> list[dict]:
    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT id, sale_date, customer_name, item_description, amount, payment_method
            FROM sales
            ORDER BY sale_date DESC, id DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
        return [dict(row) for row in rows]


def get_sale_by_id(app: Flask, sale_id: int) -> dict | None:
    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            """
            SELECT id, sale_date, customer_name, item_description, amount, payment_method
            FROM sales
            WHERE id = ?
            """,
            (sale_id,),
        ).fetchone()
        return dict(row) if row else None


def get_summary_metrics(app: Flask) -> dict:
    today = date.today()
    week_start = today - timedelta(days=today.weekday())
    month_start = today.replace(day=1)

    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        daily_income = conn.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM sales WHERE sale_date = ?",
            (today.isoformat(),),
        ).fetchone()[0]
        weekly_income = conn.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM sales WHERE sale_date >= ?",
            (week_start.isoformat(),),
        ).fetchone()[0]
        monthly_income = conn.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM sales WHERE sale_date >= ?",
            (month_start.isoformat(),),
        ).fetchone()[0]

    return {
        "daily_income": daily_income,
        "weekly_income": weekly_income,
        "monthly_income": monthly_income,
    }


def get_weekly_breakdown(app: Flask) -> list[dict]:
    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT strftime('%Y-W%W', sale_date) AS week_label,
                   ROUND(SUM(amount), 2) AS total
            FROM sales
            GROUP BY week_label
            ORDER BY week_label DESC
            LIMIT 8
            """
        ).fetchall()
    return [dict(row) for row in rows]


def get_monthly_breakdown(app: Flask) -> list[dict]:
    with closing(sqlite3.connect(app.config["DATABASE"])) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """
            SELECT strftime('%Y-%m', sale_date) AS month_label,
                   ROUND(SUM(amount), 2) AS total
            FROM sales
            GROUP BY month_label
            ORDER BY month_label DESC
            LIMIT 6
            """
        ).fetchall()
    return [dict(row) for row in rows]


app = create_app()


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
